package prolab2proje;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class oyunEkrani extends javax.swing.JFrame {

    Kullanici kull = new Kullanici();
    Bilgisayar bilg = new Bilgisayar();
    Test t = new Test();

    int a, b, c, d, e, f, g, h;
    int a1, b1, c1, d1, e1, f1, g1, h1;
    int aranan;
    String secilen_ozellik;
    int secilen_oyuncu;
    int hamle, kskor, bskor;

    DefaultTableModel dtm = new DefaultTableModel();

    public oyunEkrani() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        t.kartAtaKullanici(kull);
        t.kartAtaBilgisayar(bilg);

        //kullanicinin listesindeki kartların, sporcuListesi arraylistindeki index değerleri randomlarda tutulmuştu
        a = t.randomlar1[0];
        b = t.randomlar1[1];
        c = t.randomlar1[2];
        d = t.randomlar1[3];
        e = t.randomlar1[4];
        f = t.randomlar1[5];
        g = t.randomlar1[6];
        h = t.randomlar1[7];

        //bilgisayarın listesindeki kartların, sporcuListesi arraylistindeki index değerleri randomlarda tutulmuştu
        a1 = t.randomlar2[0];
        b1 = t.randomlar2[1];
        c1 = t.randomlar2[2];
        d1 = t.randomlar2[3];
        e1 = t.randomlar2[4];
        f1 = t.randomlar2[5];
        g1 = t.randomlar2[6];
        h1 = t.randomlar2[7];

        t.sporcu_kartOlustur();
        t.sporcu_olustur();
        setButtonIcons();

        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{kskor, bskor});

        // t.bilgKartSec(secilen_oyuncu);
        //aranan=t.bilgKartSec(secilen_oyuncu);
        // setImage2(t.sporcuImages.get(aranan));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 450));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 320, 450));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 320, 450));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 320, 450));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 320, 450));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 320, 450));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 320, 450));

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, 320, 450));

        jButton9.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton9.setText("Bilgisayarın Kartları");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 590, 200, 300));

        jButton10.setText("jButton10");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 600, 200, 300));

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 610, 200, 300));

        jButton12.setText("jButton12");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 620, 200, 300));

        jButton13.setText("jButton13");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 630, 200, 300));

        jButton14.setText("jButton14");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 640, 200, 300));

        jButton15.setText("jButton15");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 650, 200, 300));

        jButton16.setText("jButton16");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 660, 200, 300));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Kullanicinin SeçtiGi Kart");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 50, 320, 450));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Bilgisayarın Seçtigi kart");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 500, 320, 450));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 460, 260, 60));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel4.setText("Kullanicinin Kartları");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 530, 40));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jLabel5.setText("Seçilen Özellik:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 200, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kullanici skor", "Bilgisayarskor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 30, 280, 380));

        jButton17.setText("Skoru Güncelle");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 410, 160, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setImage(t.sporcuImages.get(a));
        secilen_oyuncu = a;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_basketbolcu(aranan, a);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton1.setVisible(false);
            /* if(aranan<8)//basketi;
             {
                 if(t.sporcuImages.get(aranan)==jButton9.getIcon())
                     jButton9.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton10.getIcon())
                     jButton10.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton11.getIcon())
                     jButton11.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton12.getIcon())
                     jButton12.setVisible(false);
                 
             }
             
             else
             {
                 if(t.sporcuImages.get(aranan)==jButton13.getIcon())
                     jButton13.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton14.getIcon())
                     jButton14.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton15.getIcon())
                     jButton15.setVisible(false);
                 if(t.sporcuImages.get(aranan)==jButton16.getIcon())
                     jButton16.setVisible(false);
             }*/
        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setImage(t.sporcuImages.get(b));
        secilen_oyuncu = b;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_basketbolcu(aranan, b);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton2.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setImage(t.sporcuImages.get(c));
        secilen_oyuncu = c;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_basketbolcu(aranan, c);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton3.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setImage(t.sporcuImages.get(d));
        secilen_oyuncu = d;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_basketbolcu(aranan, d);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton4.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setImage(t.sporcuImages.get(e));
        secilen_oyuncu = e;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_futbolcu(aranan, e);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton5.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setImage(t.sporcuImages.get(f));
        secilen_oyuncu = f;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_futbolcu(aranan, f);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton6.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setImage(t.sporcuImages.get(g));
        secilen_oyuncu = g;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_futbolcu(aranan, g);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton7.setVisible(false);

        }
         else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        setImage(t.sporcuImages.get(h));
        secilen_oyuncu = h;
        aranan = t.bilgKartSec(secilen_oyuncu);
        setImage2(t.sporcuImages.get(aranan));
        secilen_ozellik = t.karsilastir_futbolcu(aranan, h);
        jLabel3.setText(secilen_ozellik);
        if (secilen_ozellik != null) {
            jButton8.setVisible(false);
        }
        
        else if(secilen_ozellik==null)
        {
           JOptionPane.showMessageDialog(null,"İstenen posizyon için değerler eşit! Yeniden kart seçiniz.");
        }
          


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // kullanmıyoruz
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        //skoru güncelleme butonu

        dtm.addRow(new Object[]{t.skor_kullanici, t.skor_bilgisayar});


    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyunEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void setButtonIcons() {

        jButton1.setIcon(t.sporcuImages.get(a));
        jButton2.setIcon(t.sporcuImages.get(b));
        jButton3.setIcon(t.sporcuImages.get(c));
        jButton4.setIcon(t.sporcuImages.get(d));
        jButton5.setIcon(t.sporcuImages.get(e));
        jButton6.setIcon(t.sporcuImages.get(f));
        jButton7.setIcon(t.sporcuImages.get(g));
        jButton8.setIcon(t.sporcuImages.get(h));

        /*  Bilgisayarın kart listesi
        jButton9.setIcon(t.sporcuImages.get(a1));
        jButton10.setIcon(t.sporcuImages.get(b1));
        jButton11.setIcon(t.sporcuImages.get(c1));
        jButton12.setIcon(t.sporcuImages.get(d1));
        jButton13.setIcon(t.sporcuImages.get(e1));
        jButton14.setIcon(t.sporcuImages.get(f1));
        jButton15.setIcon(t.sporcuImages.get(g1));
        jButton16.setIcon(t.sporcuImages.get(h1)); */
    }

    private void setImage(ImageIcon icon) {

        // ImageIcon icon = new ImageIcon(path);
        Image image = icon.getImage().getScaledInstance(320, 450, Image.SCALE_SMOOTH);
        icon.setImage(image);
        jLabel1.setIcon(icon);
        jLabel1.setText("");

    }

    private void setImage2(ImageIcon icon) //bilgisayarın seçtiği kart
    {
        Image image = icon.getImage().getScaledInstance(320, 450, Image.SCALE_SMOOTH);
        icon.setImage(image);
        jLabel2.setIcon(icon);
        jLabel2.setText("");
    }

    private String ToString(int secilen_ozellik) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
